Add runtime warning
miquido/MQ-iOS pull request #24
Opened 2022-07-18 14:27 UTC by KaQuMiQ

2022-08-02 12:46 UTC, mbalawajdermq commented on Sources/MQ/Errors/TheError.swift
> +	/// Show a runtime warning with this errror as a cause.
errror

2022-08-02 12:49 UTC, mbalawajdermq requested changes
single typo

2022-08-02 12:51 UTC, mbalawajdermq approved these changes

2022-08-03 06:56 UTC, KaQuMiQ commented on Sources/MQ/Errors/TheError.swift
> +	/// Show a runtime warning with this errror as a cause.
fixed

2022-08-03 08:24 UTC, mbalawajdermq approved these changes

2022-08-03 08:33 UTC, merged